routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductsController');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::post('/cart', 'CartController@store')->name('cart.store');
Route::delete('/cart/{id}', 'CartController@destroy')->name('cart.destroy');
Route::patch('/cart/{id}', 'CartController@update')->name('cart.update');

Route::get('/results', 'SearchController@search')->name('search');

Route::get('/checkout', 'CheckoutController@index')->name('checkout');

Route::post('/payment', 'CheckoutController@payment')->name('payment');

Route::post('/subscribeToNewsletter','SubscriptionController@subscribe')->name('subscribe');

Route::get('/myAccount','PagesController@myAccount')->name('myAccount');

Route::get('/myOrderHistory','PagesController@myOrderHistory')->name('orderHistory');

Route::get('/orders/{id}','PagesController@viewOrder')->name('viewOrder');

resources/views/pages/alreadySubscribed.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
    <div id="pageTitle">
        <div class="text-light" id="currentPageLabel">
            <h1>Newsletter Subscription</h1>
        </div>
    </div>
</section>
@endsection

@section('content')
<div class="container">
    <div class="row mb-30">
        <div class="col">
            <h2>Notice</h2>
            <p>This email has already been subscribed to our newsletter </p>
            <a href="/">Back to landing page</a>
        </div>
    </div>
</div>
@endsection

resources/views/pages/cart.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
        <div id="pageTitle">
            <div class="text-light" id="currentPageLabel">
                <h1>Cart</h1>
            </div>
        </div>
</section>
@endsection

@section('content')
<div class="container">
    <h1>Shopping Cart</h1>
    @if(isset($successMsg))
    <div class="alert alert-success" role="alert">
        {{$successMsg}}
    </div>
    @endif
    @if(isset($errorMsg))
    <div class="alert alert-warning" role="alert">
        {{$errorMsg}}
    </div>
    @endif
    @if(Cart::count()>0)
    <h2>{{Cart::count()}} item(s) in your cart</h2>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Name</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Price</th>
                    <th scope="col">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach(Cart::content() as $item)
                <tr>
                <td><a href="/products/{{$item->model->id}}"><img src="{{$item->model->picture}}" alt="{{$item->name}}" width="136px" height="136px"></a></td>
                    <td><a href="/products/{{$item->model->id}}">{{$item->name}}</a></td>
                    <td>
                        <form action="{{route('cart.update',$item->rowId)}}" method="POST">
                            {{ csrf_field() }}
                            {{method_field("PATCH")}}
                            <input type="hidden" name="id" value="{{$item->id}}">
                            <input class="mt-1" type="number" name="qty" value="{{$item->qty}}" min="1" max="5" id="qty{{$item->id}}">
                            <button class="btn btn-dark mt-1" type="submit">
                                Update
                            </button>
                        </form>
                    </td>
                    <td>${{$item->price}}</td>
                    <td>
                        <form action="{{route('cart.destroy',$item->rowId)}}" method="POST">
                            {{ csrf_field() }}
                            {{method_field("DELETE")}}
                            <input type="hidden" name="id" value="{{$item->id}}">
                            <input type="hidden" name="qty" value="{{$item->qty}}">
                            <button class="btn btn-dark" type="submit">
                                <i class="fa fa-trash" aria-hidden="true" id="trash{{$item->id}}"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                @endforeach
                <tr>
                    <td colspan="4"><span class="bold"> Subtotal: </span> ${{Cart::subtotal()}}</td>
                </tr>
                </tr>
                <td colspan="4"><span class="bold">Tax: </span> ${{Cart::tax()}}</td>
                </tr>
                <tr>
                    <td colspan="4"><span class="bold">Total: </span>${{Cart::total()}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <a href="{{url('/products')}}"><button class="btn btn-dark">Back to shopping </button></a>
    <a href="{{url('/checkout')}}"><button class="btn btn-dark mt-2">Checkout</button></a>
    @else
    <h2>0 item in your cart</h2>
    @endif
</div>
@endsection

resources/views/pages/checkout.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
    <div id="pageTitle">
        <div class="text-light" id="currentPageLabel">
            <h1>Checkout</h1>
        </div>
    </div>
</section>
@endsection

@section('content')
<div class="container">
    @if(isset($errorMsg))
    <div class="alert alert-warning" role="alert">
        {{$errorMsg}}
    </div>
    @endif
    <div class="row">
        <div class="col-lg-8">
            <form method="POST" action="{{ route('payment') }}">
                @csrf
                <h1>Billing Information</h1>
                <div class="form-group">
                    <label for="firstName">First Name</label>
                    <input class="form-control" type="text" name="firstName" required>
                </div>
                <div class="form-group">
                    <label for="lastName">Last Name</label>
                    <input class="form-control" type="text" name="lastName" required>
                </div>
                <div class="form-group">
                    <label for="address">Address</label>
                    <input class="form-control" type="text" name="address" required>
                </div>
                <div class="form-group">
                    <label for="country">Country</label>
                    <input class="form-control" type="text" name="country" required>
                </div>
                <div class="form-group">
                    <label for="city">City</label>
                    <input class="form-control" type="text" name="city" required>
                </div>
                <div class="form-group">
                    <label for="state">State/Province</label>
                    <input class="form-control" type="text" name="state" required>
                </div>
                <div class="form-group">
                    <label for="zipcode">Zip Code/Postal Code</label>
                    <input class="form-control" type="text" name="zipcode" required>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input class="form-control" type="email" name="email" required>
                </div>
                <h1>Payment Options</h1>
                <div class="form-group">
                    <label for="nameoncard">Full Name On Card</label>
                    <input class="form-control" type="text" name="nameOnCard" required>
                </div>
                <div class="form-group">
                    <label for="cardNumb">Card Number</label>
                    <input class="form-control" type="text" name="cardNumb" required>
                </div>
                <div class="row">
                    <div class="form-group col-sm-7">
                        <label for="expirationDate">Expiration Date</label>
                        <div class="form-inline">
                            <input class="form-control mr-4" type="number" name="expMonth" id="expFieldMonth" min="1" max="12"
                                placeholder="MM" required>
                            <input class="form-control" type="number" name="expYear" id="expFieldYear" min="2018" max="3000"
                                placeholder="YYYY" required>
                        </div>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="cvc">CVC</label>
                        <div class="form-inline">
                            <input class="form-control" type="number" name="cvc" pattern="[0-9]{3}" required>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-dark mt-2 mb-3">Complete Order</button>
            </form>
        </div>
        <div class="col-lg-4">
            <h1>Cart Summary</h1>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(Cart::content() as $item)
                        <tr>
                            <td><a href="/products/{{$item->model->id}}">{{$item->name}}</a></td>
                            <td>{{$item->qty}}</td>
                            <td>${{$item->price}}</td>
                        </tr>
                        @endforeach
                        <tr>
                            <td colspan="4"><span class="bold"> Subtotal: </span> ${{Cart::subtotal()}}</td>
                        </tr>
                        </tr>
                        <td colspan="4"><span class="bold">Tax: </span> ${{Cart::tax()}}</td>
                        </tr>
                        <tr>
                            <td colspan="4"><span class="bold">Total: </span>${{Cart::total()}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/index.blade.php
<!DOCTYPE html>
<html lang="eng">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width" />
	<title>Musician's Center</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
</head>
<body>
    <header>
    @include('inc.navbar')
              <section id="slogan">
                <div class="text-light">
                    <h1>Become the rockstar you always wanted to be</h1>
                    <h3>Your #1 destination for the best musical instruments, gear and exclusive content to help you get the sound you’re after</h3>
                    <a href="/products"><button class="btn btn-outline-light" id="shopNowBtn">Shop now</button></a>
                </div>
              </section>
    </header>
    <div class="container">
      <section class="mainContent" id="featuredProducts">
          <h1>Featured products</h1>
          <div class="featuredProductsContainer">
              <div class="row">
                  <div class="col-lg-3">
                      <div class="featuredElement" id="featured1">
                          <a href="/products/1"><img class="featuredImg" src="{{URL::asset('/imgs/guitar1.jpg')}}" alt="guitar 1"/></a>
                          <p class="featuredProductTitle">Epiphone Les Paul Special II Plus</p>
                          <p class="featuredProductPrice">CAD 326.36</p>
                      </div>
                  </div>
                  <div class="col-lg-3">
                        <div class="featuredElement" id="featured2">
                            <a href="/products/2"><img class="featuredImg" src="{{URL::asset('/imgs/guitar2.jpg')}}" alt="guitar 2"/></a>
                            <p class="featuredProductTitle">Gibson Les Paul Traditional 2019</p>
                            <p class="featuredProductPrice">CAD 3,989.05</p>
                        </div>
                  </div>
                  <div class="col-lg-3">
                        <div class="featuredElement" id="featured3">
                            <a href="products/3"><img class="featuredImg" src="{{URL::asset('/imgs/guitar3.jpg')}}" alt="guitar 3"/></a>
                            <p class="featuredProductTitle">G&L Tribute Legacy</p>
                            <p class="featuredProductPrice">CAD 711.16</p>
                        </div>
                  </div>
                  <div class="col-lg-3">
                        <div class="featuredElement" id="featured4">
                            <a href="products/4"><img class="featuredImg" src="{{URL::asset('/imgs/guitar4.jpg')}}" alt="guitar 4"/></a>
                            <p class="featuredProductTitle">Takamine GD-30CE 12-String</p>
                            <p class="featuredProductPrice">CAD 641.31</p>
                        </div>
                  </div>
              </div>
          </div>
      </section>
      <section class="mainContent" id="contact">
          <h1>Newsletter</h1>
          <form action="{{route('subscribe')}}" method="POST" id="newsletterForm">
              @csrf
              <input type="email" name="email" id="subscriptionBox" placeholder="email address" required>
              <button type="submit" value="Subscribe" name="subscribe">Subscribe</button>
          </form>
      </section>
    </div>
    @include('inc.footer')
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
    <script type="text/javascript" src="{{ asset('js/custom.js') }}"></script>
</body>
</html>

resources/views/pages/myAccount.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
        <div id="pageTitle">
            <div class="text-light" id="currentPageLabel">
                <h1>My Account</h1>
            </div>
        </div>
</section>
@endsection

@section('content')
<div class="container">
    <div class="row mb-30">
        <div class="col">
        <h2>Welcome {{Auth::user()->email}}</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h4>Recent orders</h4>
            <a href="/myOrderHistory">View all order history</a>
            <div class="table-responsive">
                    <table class="table">
                      <thead>
                          <tr>
                              <th>Order Date</th>
                              <th>Order Number</th>
                              <th>Order Total</th>
                              <th>Status</th>
                              <th></th>
                          </tr>
                      </thead>
                      <tbody>
                          @foreach($recentOrders as $order)
                          <tr>
                            <td>{{$order->created_at}}</td>
                            <td>{{$order->id}}</td>
                            <td>${{number_format($order->orderTotal,2)}}</td>
                            <td>{{$order->status}}</td>
                            <td><a href="{{route('viewOrder',$order->id)}}">View details</a></td>
                          </tr>
                          @endforeach
                      </tbody>
                    </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/myOrderHistory.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
        <div id="pageTitle">
            <div class="text-light" id="currentPageLabel">
                <h1>My Order History</h1>
            </div>
        </div>
</section>
@endsection

@section('content')
<div class="container">
    <div class="row mb-30">
        <div class="col">
            <h4>My Orders</h4>
            <div class="table-responsive">
                    <table class="table">
                      <thead>
                          <tr>
                              <th>Order Date</th>
                              <th>Order Number</th>
                              <th>Order Total</th>
                              <th>Status</th>
                              <th></th>
                          </tr>
                      </thead>
                      <tbody>
                          @foreach($orderHistory as $order)
                          <tr>
                            <td>{{$order->created_at}}</td>
                            <td>{{$order->id}}</td>
                            <td>${{number_format($order->orderTotal,2)}}</td>
                            <td>{{$order->status}}</td>
                            <td><a href="{{route('viewOrder',$order->id)}}">View details</a></td>
                          </tr>
                          @endforeach
                      </tbody>
                    </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/orderDetails.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
        <div id="pageTitle">
            <div class="text-light" id="currentPageLabel">
                <h1>Order Details</h1>
            </div>
        </div>
</section>
@endsection

@section('content')
<div class="container">
    <h2>Order</h2>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Order Date</th>
                        <th scope="col">Order Number</th>
                        <th scope="col">Order Total</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{$order->created_at}}</td>
                        <td>{{$order->id}}</td>
                        <td>${{number_format($order->orderTotal,2)}}</td>
                        <td>{{$order->status}}</td>
                    </tr>
                </tbody>
            </table>
    </div>
    <h2>Billing Information</h2>
    <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Customer First Name</th>
                        <th scope="col">Customer Last Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">City</th>
                        <th scope="col">State</th>
                        <th scope="col">Zip Code</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{$order->customerFirstName}}</td>
                        <td>{{$order->customerLastName}}</td>
                        <td>{{$order->address}}</td>
                        <td>{{$order->city}}</td>
                        <td>{{$order->state}}</td>
                        <td>{{$order->zipcode}}</td>
                    </tr>
                </tbody>
            </table>
    <h2>Items ordered</h2>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Price</th>
                    <th scope="col">Tax</th>
                    <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($cartSummary as $rowId=>$product)
                    <tr>
                        <td><a href="/products/{{$product["id"]}}">{{htmlspecialchars_decode($product["name"], ENT_QUOTES)}}</a></td>
                        <td>{{$product["qty"]}}</td>
                        <td>${{$product["price"]}}</td>
                        <td>${{number_format($product["tax"],2)}}</td>
                        <td>${{number_format($product["subtotal"]+$product["tax"],2)}}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/pages/paymentSuccessful.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
        <div id="pageTitle">
            <div class="text-light" id="currentPageLabel">
                <h1>Checkout</h1>
            </div>
        </div>
</section>
@endsection

@section('content')
<div class="container">
    <div class="row mb-30">
        <div class="col">
            <h2>Order successful</h2>
            <p>Your payment has been processed and your order is complete. We will be dispatching your order soon. You will receive an email confirmation shortly.</p>
            <a href="/products">Back to shopping</a>
        </div>
    </div>
</div>
@endsection

resources/views/pages/productDetail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row border p-3">
        <div class="product-image col-lg-6 pb-3">
            <img src="{{$product->picture}}" alt='Picture not found'>
        </div>
        <div class="product-information border-left col-lg-6">
            <h1>{{htmlspecialchars_decode($product->product_name, ENT_QUOTES)}}</h1>
            <p><strong>${{$product->price}}</strong></p>
            <p>{{htmlspecialchars_decode($product->description, ENT_QUOTES)}}</p>
            @if($product->qtyInStock<1) <p><span class="text-danger">Out of stock</span> </p>
                @else
                <p><span class="text-success">In stock:</span> {{$product->qtyInStock}} left!</p>
                <form action="{{route('cart.index')}}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="productId" value="{{$product->id}}">
                    <input type="hidden" name="name" value="{{$product->product_name}}">
                    <input type="hidden" name="price" value="{{$product->price}}">
                    <label>Qty: </label>
                    <input type="number" name="qty" min="1" max="50" required>
                    <button class="btn btn-dark">Add to cart</button>
                </form>
                @endif
        </div>
    </div>
</div>
@endsection

resources/views/pages/productList.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
    <div id="pageTitle">
        <div class="text-light" id="currentPageLabel">
            <h1>Shop</h1>
        </div>
    </div>
</section>
@endsection

@section('content')
<div class="container">
    <h1>Products</h1>
    <div class="row">
        <div class="col-xl-6 mb-3">
            <form id="sort-options" action="" method="GET">
                @csrf
                <select id="sorter" name="sorter">
                    <option value="">Sort by...</option>
                    <option value="{{route('products.index',['sort'=>'byNewest'])}}">Sort by Newest</option>
                    <option value="{{route('products.index',['sort'=>'byPriceAsc'])}}">Sort by Price (low to high)</option>
                    <option value="{{route('products.index',['sort'=>'byPriceDesc'])}}">Sort by Price (high to low)</option>
                    <option value="{{route('products.index',['sort'=>'byNameAsc'])}}">Sort by Name (a-z)</option>
                    <option value="{{route('products.index',['sort'=>'byNameDesc'])}}">Sort by Name (z-a)</option>
                </select>
            </form>
        </div>
    </div>
    <div class="row">
        @if(count($products)>0)
        @foreach($products as $product)
        <div class="card">
            <article class="itemlist">
                <div class="row">
                    <aside class="col-lg-3 col-md-12 col-sm-12 pt-3">
                        <div class="d-flex justify-content-center"><a href="/products/{{$product->id}}"><img class="img-md"
                                    src="{{$product->picture}}" width="200" height="200"></a></div>
                    </aside> <!-- col.// -->
                    <div class="col-lg-6 col-md-12 col-sm-12 tm-20 pt-3">
                        <div class="pl-15 pr-15 info-block">
                            <h4 class="title"> <a href="/products/{{$product->id}}">{{htmlspecialchars_decode($product->product_name, ENT_QUOTES)}}</a> </h4>
                            <p> {{htmlspecialchars_decode($product->description, ENT_QUOTES)}} </p>
                        </div> <!-- text-wrap.// -->
                    </div> <!-- col.// -->
                    <aside class="col-lg-3 col-md-12 col-sm-12 tm-20 pt-3 price-block">
                        <div class="border-left pl-3">
                            <div class="price-wrap">
                                <span class="h3 price">$ {{$product->price}} </span>
                            </div> <!-- info-price-detail // -->
                            <p class="text-success">Free shipping</p>
                            <p>
                            </p>
                        </div> <!-- action-wrap.// -->
                    </aside> <!-- col.// -->
                </div> <!-- row.// -->
            </article> <!-- itemlist.// -->
            @endforeach
            {{ $products->appends(request()->except('page'))->links() }}
        </div>
        @else
        <p>No products found</p>
        @endif
    </div>
    @endsection

resources/views/pages/searchResults.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
        <div id="pageTitle">
            <div class="text-light" id="currentPageLabel">
            <h1>Search Results</h1>
            </div>
        </div>
</section>
@endsection

@section('content')
<div class="container">
  <h1>Search results for "{{request()->search}}"</h1>
  <div class="row">
    <div class="col-xl-6 mb-3">
        <form id="sort-options" action="" method="GET">
            @csrf
            <select id="sorter" name="sorter">
                <option value="{{route('search',['search'=>request()->search,'sort'=>'byNewest'])}}">Sort by Newest</option>
                <option value="{{route('search',['search'=>request()->search,'sort'=>'byPriceAsc'])}}">Sort by Price (low to high)</option>
                <option value="{{route('search',['search'=>request()->search,'sort'=>'byPriceDesc'])}}">Sort by Price (high to low)</option>
                <option value="{{route('search',['search'=>request()->search,'sort'=>'byNameAsc'])}}">Sort by Name (a-z)</option>
                <option value="{{route('search',['search'=>request()->search,'sort'=>'byNameDesc'])}}">Sort by Name (z-a)</option>
            </select>
        </form>
    </div>
</div>
  <div class="row">
  @if(count($results)>0)
    @foreach($results as $result)
    <div class="card">
<article class="itemlist">
	<div class="row">
		<aside class="col-lg-3 col-md-12 col-sm-12 pt-3">
			<div class="d-flex justify-content-center"><a href="/products/{{$result->id}}"><img class="img-md" src="{{$result->picture}}" width="200" height="200"></a></div>
		</aside> <!-- col.// -->
		<div class="col-lg-6 col-md-12 col-sm-12 tm-20 pt-3">
			<div class="pl-15 pr-15 info-block">
				<h4 class="title"> <a href="/products/{{$result->id}}">{{$result->product_name}}</a> </h4>
				<p> {{htmlspecialchars_decode($result->description, ENT_QUOTES)}} </p>
			</div> <!-- text-wrap.// -->
		</div> <!-- col.// -->
		<aside class="col-lg-3 col-md-12 col-sm-12 tm-20 pt-3 price-block">
			<div class="border-left pl-3">
				<div class="price-wrap">
					<span class="h3 price">$ {{$result->price}} </span>
				</div> <!-- info-price-detail // -->
				<p class="text-success">Free shipping</p>
				<p>
        </p>
			</div> <!-- action-wrap.// -->
		</aside> <!-- col.// -->
	</div> <!-- row.// -->
</article> <!-- itemlist.// -->
    @endforeach
    {{ $results->appends(request()->except('page'))->links() }}
  </div>
  @else
    <p>No products found</p>
  @endif
</div>
@endsection

resources/views/pages/subscriptionSuccessful.blade.php
@extends('layouts.app')

@section('page-title')
<section class="pageTitle">
    <div id="pageTitle">
        <div class="text-light" id="currentPageLabel">
            <h1>Newsletter Subscription</h1>
        </div>
    </div>
</section>
@endsection

@section('content')
<div class="container">
    <div class="row mb-30">
        <div class="col">
            <h2>Subscription successful</h2>
            <p>Thank you for subscribing to our newsletter!</p>
            <a href="/">Back to landing page</a>
        </div>
    </div>
</div>
@endsection